FROM ubuntu
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository main
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential gfortran zlib1g-dev xauth r-base-core pkg-config \
    libreadline-dev libpng-dev libpcre3-dev libpcre2-dev libncurses5-dev \
    liblzma-dev liblapack-dev libatlas-base-dev r-base-dev wget make \
    libjpeg-dev libicu-dev libbz2-dev libblas-dev libcurl4-openssl-dev
RUN useradd docker \
	&& mkdir /home/docker \
	&& chown docker:docker /home/docker \
	&& adduser docker staff
WORKDIR /app/Downloads
RUN wget https://cran.r-project.org/src/base/R-3/R-3.4.4.tar.gz
RUN tar -xf R-3.4.4.tar.gz
WORKDIR /app/Downloads/R-3.4.4
RUN ./configure --with-x=no
RUN make
RUN make install
RUN R -e "install.packages('methods',dependencies=TRUE, repos='http://cran.rstudio.com/')"
